spring:
  application:
    name: dbrepli
#  datasource:
#    url: jdbc:mysql://mysql-master:3306/dbrepli?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1111
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  jpa:
    properties:
      hibernate:
        show_sql: false
        generate-ddl: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.MySQLDialect

database:
  url: jdbc:mysql://127.0.0.1:3306/repli?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  username: root
  password: 1111
  slave:
    slave1:
      name: slave
      url: jdbc:mysql://127.0.0.1:3307/repli?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: root
      password: 1111
